spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 020910
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
      id-type: assign_id
Reggie:
  path: E:\reggie\image\